apiVersion: v1
kind: Service
metadata:
  name: {{ include "distribution-service.fullname" . }}
  labels:
    {{- include "distribution-service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "distribution-service.selectorLabels" . | nindent 4 }}
  ports:
    - name: distribution
      port: {{ .Values.service.distributionPort }}
      targetPort: {{ .Values.distribution.port }}
      protocol: TCP
{{- if .Values.dataService.enabled }}
    - name: data-service
      port: {{ .Values.service.dataServicePort }}
      targetPort: {{ .Values.dataService.port }}
      protocol: TCP
{{- end }}