import assert from "node:assert/strict";
import { createPublicKey, verify } from "node:crypto";
import { readFileSync, readdirSync } from "node:fs";
import { describe, it } from "node:test";
import path from "node:path";
import { fileURLToPath } from "node:url";

import { verifyX509Ed25519Leaf } from "../dist/cert-chain.js";
import { gateBundleLoad } from "../dist/bundle-load-gate.js";

/**
 * #264: fixtures are committed bytes, not certificates generated by the openssl
 * CLI at run time. The old fixture shelled out to whatever openssl the machine
 * happened to have, so the only test covering the ADR-024 trust chain passed
 * locally and failed on CI with "no Ed25519 SPKI in tbs" — taking `pnpm test`
 * red and, because the workflow runs steps in order, silently skipping the
 * governance gate, the verify probes and `rn doctor`.
 *
 * See fixtures/cert-chain/README.md for provenance and for the parser bug the
 * pinned bytes currently mask.
 */
const FIXTURE_DIR = path.resolve(
  path.dirname(fileURLToPath(import.meta.url)),
  "fixtures/cert-chain",
);

const readFixture = (name: string): string =>
  readFileSync(path.join(FIXTURE_DIR, name), "utf8").trim();

const LEAF_PEM = readFixture("leaf.crt");
const OTHER_RCA_PUBKEY_HEX = readFixture("other-rca-pubkey-hex.txt");
const RCA_PUBKEY_HEX = readFixture("rca-pubkey-hex.txt");
const LEAF_PUBKEY_HEX = readFixture("leaf-pubkey-hex.txt");
/**
 * The leaf private key is deliberately NOT committed: this repo is a
 * trust-root/OTA platform (ADR-017/018/024) and a key-shaped file in the tree
 * invites exactly the ambiguity those ADRs remove. The test needs one fixed
 * signature over one fixed payload, so that signature is committed instead.
 */
const LEAF_SIGNATURE_B64 = readFixture("leaf1-signature.txt");

/** Payload `leaf1-signature.txt` is a leaf-key signature over. */
const DIGEST = "a".repeat(64);
const SEAL_PAYLOAD = `release-1:js-update:${DIGEST}`;

/** Raw Ed25519 public key (32 bytes) as a Node KeyObject. */
function ed25519PublicKeyFromHex(hex: string) {
  // 302a300506032b6570032100 = SEQUENCE{ SEQUENCE{OID 1.3.101.112}, BIT STRING(32) }
  const spki = Buffer.from(`302a300506032b6570032100${hex}`, "hex");
  return createPublicKey({ key: spki, format: "der", type: "spki" });
}

describe("cert-chain fixtures (#264)", () => {
  it("committed signature verifies against the committed leaf certificate", () => {
    // Guards the fixture set itself: if someone regenerates certs without
    // regenerating the signature, the certificates would still parse and every
    // other test here would quietly become vacuous.
    const ok = verify(
      null,
      Buffer.from(SEAL_PAYLOAD),
      ed25519PublicKeyFromHex(LEAF_PUBKEY_HEX),
      Buffer.from(LEAF_SIGNATURE_B64, "base64"),
    );
    assert.equal(ok, true, "leaf1-signature.txt does not match leaf-pubkey-hex.txt");
  });

  it("the two RCAs are actually different keys", () => {
    // The wrong-RCA cases are only meaningful if the keys differ; pinning this
    // stops a fixture regeneration from silently making them no-ops.
    assert.notEqual(RCA_PUBKEY_HEX, OTHER_RCA_PUBKEY_HEX);
  });

  it("this test cannot shell out to a CLI", () => {
    const source = readFileSync(
      new URL("./cert-chain.test.ts", import.meta.url),
      "utf8",
    );
    // Assemble the needle so this assertion's own text cannot match itself.
    const spawnApi = ["spawn", "Sync"].join("");
    const execApi = ["execFile", "Sync"].join("");
    assert.ok(
      !source.includes(spawnApi) && !source.includes(execApi),
      "run-time certificate generation is what made this gate environment-dependent (#264)",
    );
  });

  it("commits no private key", () => {
    // Public artifacts only: a key-shaped file in this tree invites exactly the
    // trust-root ambiguity ADR-017/018/024 exist to remove. The one signature
    // the suite needs is committed as bytes instead.
    const keyFiles = readdirSync(FIXTURE_DIR).filter((f) => f.endsWith(".key"));
    assert.deepEqual(keyFiles, []);
  });
});

describe("ADR-024 cert-chain verify (X.509 Ed25519 leaf → RCA)", () => {
  it("accepts a valid RCA-signed leaf with matching key", () => {
    const r = verifyX509Ed25519Leaf(LEAF_PEM, RCA_PUBKEY_HEX, LEAF_PUBKEY_HEX);
    assert.equal(r.ok, true, JSON.stringify(r));
    if (r.ok) assert.equal(r.leafPubkeyHex, LEAF_PUBKEY_HEX);
  });

  it("finds the SPKI in a versionless (v1) certificate — by tag, not by index (#264)", () => {
    // versionless-leaf.crt is this same leaf with its OPTIONAL [0] version
    // element removed, which is the shape the CI runner's OpenSSL emitted. Its
    // signature no longer covers the modified tbs, so a rejection is correct —
    // but it must come from the root-CA signature check, i.e. AFTER the SPKI
    // was found and matched the expected key. Before the fix the parser bailed
    // out with "no Ed25519 SPKI in tbs" (a fixed `i = 6` scan skips the 5th
    // child), so valid versionless certificates were unverifiable and `pnpm
    // test` went red on CI, silently skipping every later CI step.
    const r = verifyX509Ed25519Leaf(
      readFixture("versionless-leaf.crt"),
      RCA_PUBKEY_HEX,
      LEAF_PUBKEY_HEX,
    );
    assert.equal(r.ok, false);
    if (!r.ok) {
      assert.notEqual(
        r.reason,
        "no Ed25519 SPKI in tbs",
        "the parser must locate the SPKI by tag walk, not at a fixed tbs index",
      );
      assert.match(r.reason, /root-CA signature/);
    }
  });

  it("rejects when the expected leaf key mismatches the certificate", () => {
    const r = verifyX509Ed25519Leaf(LEAF_PEM, RCA_PUBKEY_HEX, "00".repeat(32));
    assert.equal(r.ok, false);
  });

  it("rejects when the RCA key does not sign the leaf (fail-closed)", () => {
    const r = verifyX509Ed25519Leaf(
      LEAF_PEM,
      OTHER_RCA_PUBKEY_HEX,
      LEAF_PUBKEY_HEX,
    );
    assert.equal(r.ok, false);
  });

  it("rejects garbage input without throwing", () => {
    const r = verifyX509Ed25519Leaf("not a cert", "00".repeat(32));
    assert.equal(r.ok, false);
  });
});

describe("ADR-024 gateBundleLoad cert mode (seal signed by leaf, verified under RCA)", () => {
  it("accepts a leaf-signed seal with a valid cert chain; rejects wrong RCA", () => {
    const base = {
      candidate: {
        business_module: "main",
        update_id: "main-x",
        hbcBytecodeVersion: 96,
        required_capabilities: [],
        target_artifact_lines: ["pure-rn-greenfield"],
        release_gate: "js-standard",
        runtime_fingerprint: {
          engine: {
            id: "react-native",
            version: "0.87.0+hermes-v1+newarch+codegen-locked",
            hermesVmIdentity: "hermes-v1@compiler-id",
            hbcBytecodeVersion: 96,
            newArchFlags: { bridgeless: true, fabric: true, turboModules: true },
          },
          nativeAbiSurfaceDigest: "sha256:abi",
        },
      },
      signature: `pem:ed25519:${LEAF_SIGNATURE_B64}`,
      release_id: "release-1",
      artifact_kind: "js-update",
      expectedDigest: DIGEST,
    };
    const fp = {
      engine: {
        id: "react-native",
        version: "0.87.0+hermes-v1+newarch+codegen-locked",
        hermesVmIdentity: "hermes-v1@compiler-id",
        hbcBytecodeVersion: 96,
        newArchFlags: { bridgeless: true, fabric: true, turboModules: true },
      },
      nativeAbiSurfaceDigest: "sha256:abi",
    };
    const host = {
      artifact_line: "pure-rn-greenfield",
      runtime_fingerprint: fp,
      capability_set: [],
      hbcBytecodeVersion: 96,
      channel_js_allowed: true,
    };
    const ok = gateBundleLoad(
      {
        ...base,
        publicKeys: [RCA_PUBKEY_HEX],
        certChain: { leafCertPem: LEAF_PEM, leafPubkeyHex: LEAF_PUBKEY_HEX },
      },
      host,
    );
    assert.equal(ok.ok, true, JSON.stringify(ok));
    const badRca = gateBundleLoad(
      {
        ...base,
        publicKeys: [OTHER_RCA_PUBKEY_HEX],
        certChain: { leafCertPem: LEAF_PEM, leafPubkeyHex: LEAF_PUBKEY_HEX },
      },
      host,
    );
    assert.equal(badRca.ok, false);
    // stage-0 fallback still works (no certChain)
    const stage0 = gateBundleLoad(
      {
        ...base,
        publicKeys: [LEAF_PUBKEY_HEX],
      },
      host,
    );
    assert.equal(stage0.ok, true);
  });
});

describe("ADR-024 stage-3 requireCert (sunset gate)", () => {
  it("fails when requireCert and no certChain (legacy path disabled)", () => {
    const host = { artifact_line: "pure-rn-greenfield", runtime_fingerprint: { engine: { id: "react-native", version: "0.87.0+hermes-v1+newarch+codegen-locked", hermesVmIdentity: "h", hbcBytecodeVersion: 96, newArchFlags: { bridgeless: true, fabric: true, turboModules: true } }, nativeAbiSurfaceDigest: "sha256:abi" }, capability_set: [], hbcBytecodeVersion: 96, channel_js_allowed: true };
    const base = {
      candidate: { business_module: "main", update_id: "main-y", runtime_fingerprint: { engine: { id: "react-native", version: "0.87.0+hermes-v1+newarch+codegen-locked", hermesVmIdentity: "h", hbcBytecodeVersion: 96, newArchFlags: { bridgeless: true, fabric: true, turboModules: true } }, nativeAbiSurfaceDigest: "sha256:abi" }, hbcBytecodeVersion: 96, required_capabilities: [], target_artifact_lines: ["pure-rn-greenfield"], release_gate: "js-standard" },
      signature: "pem:ed25519:AAAA", // never reached — requireCert fails first
      release_id: "r", artifact_kind: "js-update", expectedDigest: "a".repeat(64),
      publicKeys: ["00".repeat(32)],
      requireCert: true,
    };
    const r = gateBundleLoad(base, host);
    assert.equal(r.ok, false);
    assert.match(JSON.stringify(r), /requireCert/);
  });
});
