/**
 * Host Metro resolver generation (ADR-021/D2 — 声明驱动, no hardcoded scope).
 *
 * Reads the dev-session's DECLARED module identity (root + packageName from C2)
 * and the host's own package.json deps (singletons). Never assumes `@tiangong/`
 * scope or `../<id>` sibling layout — modules may live anywhere and use any scope.
 */
import { existsSync, mkdirSync, readFileSync, realpathSync as fsRealpathSync, writeFileSync } from "node:fs";
import path from "node:path";

import type { DevSessionConfig, ModuleDevBinding } from "@client-platform/core";
import { loadDevSessionConfig } from "./dev-session-config.js";

export const HOST_METRO_RESOLVER_RELATIVE = path.join(
  ".rn",
  "metro",
  "host-resolver.cjs",
);

export function hostMetroResolverPath(projectRoot: string): string {
  return path.join(projectRoot, HOST_METRO_RESOLVER_RELATIVE);
}

function readJson(file: string): Record<string, unknown> | null {
  try {
    return JSON.parse(readFileSync(file, "utf8")) as Record<string, unknown>;
  } catch {
    return null;
  }
}

/**
 * Business modules → extraNodeModules entries from DECLARED packageName + root.
 * A module is included only when it self-declared both (C2 dev-session binding).
 */
function declaredModuleAliases(
  modules: Readonly<Record<string, ModuleDevBinding>>,
): Record<string, string> {
  const out: Record<string, string> = {};
  for (const binding of Object.values(modules)) {
    if (binding.root && binding.packageName) {
      out[binding.packageName] = binding.root;
    }
  }
  return out;
}

/** Host singletons: pin the host's own deps to its node_modules (singleton React). */
function hostSingletonAliases(
  hostRoot: string,
  modules: Readonly<Record<string, ModuleDevBinding>>,
): Record<string, string> {
  const hostPkg = readJson(path.join(hostRoot, "package.json"));
  const deps = hostPkg?.dependencies;
  const out: Record<string, string> = {};
  if (deps && typeof deps === "object") {
    for (const dep of Object.keys(deps as Record<string, unknown>)) {
      const p = path.join(hostRoot, "node_modules", dep);
      if (existsSync(p) && !out[dep]) {
        // resolve symlinks (platform packages) to the real path — Metro does not
        // follow symlinked package subpaths like @client-platform/core/ota
        try {
          out[dep] = fsRealpathSync(p);
        } catch {
          out[dep] = p;
        }
      }
    }
  }
  return out;
}

export interface HostMetroResolverInput {
  projectRoot: string;
}

export function renderHostMetroResolverCjs(config: DevSessionConfig, hostRoot: string): string {
  const modules = config.modules ?? {};
  const businessAliases = declaredModuleAliases(modules);
  const singletons = hostSingletonAliases(hostRoot, modules);
  const extraNodeModules: Record<string, string> = {
    ...businessAliases,
    ...singletons,
  };
  // watch business module roots + out-of-project singleton (platform package) realpaths
  const outOfProject = Object.values(extraNodeModules).filter(
    (p) => !p.startsWith(hostRoot),
  );
  const watchFolders = [
    ...new Set([...Object.values(businessAliases), ...outOfProject]),
  ];
  // pnpm: add each out-of-project workspace's .pnpm virtual store so Metro can
  // follow package symlinks (e.g. @noble/ed25519 → .pnpm/@noble+ed25519@…).
  // F14/SEAM-2: dedup — multiple platform packages share the same .pnpm store.
  for (const p of outOfProject) {
    const pnpm = path.join(path.resolve(p, "../.."), "node_modules", ".pnpm");
    if (existsSync(pnpm) && !watchFolders.includes(pnpm)) {
      watchFolders.push(pnpm);
    }
  }
  // node_modules paths: project + out-of-project platform package node_modules + workspace root
  const nodeModulesPaths = [path.join(hostRoot, "node_modules")];
  for (const p of outOfProject) {
    for (const nm of [
      path.join(p, "node_modules"), // per-package (pnpm isolated)
      path.join(path.resolve(p, "../.."), "node_modules"), // workspace root
    ]) {
      if (existsSync(nm) && !nodeModulesPaths.includes(nm)) {
        nodeModulesPaths.push(nm);
      }
    }
  }

  return `/**
 * Auto-generated by @client-platform/rn — Host Metro resolver (singleton React policy).
 * Regenerated by: rn dev · rn module register. Declared from dev-session module
 * identity (packageName + root) + host package.json deps. No hardcoded scope.
 */
"use strict";
const path = require("node:path");

const WATCH_FOLDERS = ${JSON.stringify(watchFolders, null, 2)};
const NODE_MODULES_PATHS = ${JSON.stringify(nodeModulesPaths, null, 2)};
const EXTRA_NODE_MODULES = ${JSON.stringify(extraNodeModules, null, 2)};
const DISABLE_HIERARCHICAL_LOOKUP = true;

function load() {
  return {
    watchFolders: WATCH_FOLDERS,
    resolver: {
      nodeModulesPaths: NODE_MODULES_PATHS,
      extraNodeModules: EXTRA_NODE_MODULES,
      disableHierarchicalLookup: DISABLE_HIERARCHICAL_LOOKUP,
    },
  };
}

module.exports = { load };
`;
}

/** Regenerate the host's `.rn/metro/host-resolver.cjs` from declared identity. */
export function writeHostMetroResolver(projectRoot: string): string {
  const session = loadDevSessionConfig(projectRoot);
  if (!session) {
    throw new Error("no .rn/dev-session.jsonc — run rn module link first");
  }
  const file = hostMetroResolverPath(projectRoot);
  mkdirSync(path.dirname(file), { recursive: true });
  writeFileSync(file, renderHostMetroResolverCjs(session, projectRoot), "utf8");
  return file;
}
