/**
 * Industrial shell generation (ADR-021): turn a basic `rn init` app into the
 * industrial shell — ShellHost + ModuleRegistry (consuming the generated
 * registry) + OTA gate. Zero reference-host coupling (no tiangong/hermes).
 */
import {
  existsSync,
  mkdirSync,
  readFileSync,
  readdirSync,
  rmSync,
  statSync,
  symlinkSync,
  writeFileSync,
} from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

import { MANIFEST_FILENAME } from "@client-platform/core";
import { CliError, EXIT_FAIL } from "./errors.js";
import {
  ensureRuntimeConfig,
  regenerateDerivedArtifacts,
} from "./declaration-derived.js";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
// dist: packages/rn/dist/industrial-shell.js → templates at packages/rn/templates
const TEMPLATE_ROOT = path.resolve(__dirname, "../templates/industrial-shell");

export const INDUSTRIAL_SHELL_FILES = [
  "App.tsx.template",
  "shell/ShellHost.tsx.template",
  "shell/ModuleRegistry.ts.template",
  "shell/hostContext.ts.template",
  "shell/FailedUI.tsx.template",
  "shell/ota/slotPaths.ts.template",
  "metro.config.js.template",
] as const;

function renderTemplate(rel: string, defaultModuleId: string): string {
  const src = readFileSync(path.join(TEMPLATE_ROOT, rel), "utf8");
  return src.replace(/{{DEFAULT_MODULE_ID}}/g, defaultModuleId);
}

/** Read the project's default module id from its manifest (or fall back). */
function defaultModuleIdFromManifest(projectRoot: string): string {
  try {
    const raw = readFileSync(path.join(projectRoot, MANIFEST_FILENAME), "utf8");
    // minimal JSONC read: business default is "main" per topology-b; the
    // manifest doesn't carry it, so default to "main".
    void raw;
  } catch {
    /* ignore */
  }
  return "main";
}

/**
 * Apply the industrial shell to an initialized project.
 * Writes App.tsx (→ ShellHost) + shell/{ShellHost,ModuleRegistry,hostContext,FailedUI,ota/slotPaths}
 * + links the platform packages (core/shell-core/rn-engine) so the shell resolves them.
 */
/** F25: template version — bump when industrial shell templates change. Existing
 * projects can detect drift and run `rn shell refresh` to regenerate. */
export const INDUSTRIAL_TEMPLATE_VERSION = "3";

/** Write the applied template version marker (.rn/template-version.json). */
export function writeTemplateVersion(projectRoot: string): void {
  const file = path.join(projectRoot, ".rn", "template-version.json");
  mkdirSync(path.dirname(file), { recursive: true });
  writeFileSync(
    file,
    `${JSON.stringify({ schemaVersion: 1, industrialTemplateVersion: INDUSTRIAL_TEMPLATE_VERSION }, null, 2)}\n`,
    "utf8",
  );
}

/** Read the project's applied template version (null when not industrial). */
export function readTemplateVersion(projectRoot: string): string | null {
  try {
    const j = JSON.parse(
      readFileSync(
        path.join(projectRoot, ".rn", "template-version.json"),
        "utf8",
      ),
    ) as { industrialTemplateVersion?: string };
    return j.industrialTemplateVersion ?? null;
  } catch {
    return null;
  }
}

/** F25: does this project's shell drift from the current template? */
export function shellTemplateDrift(projectRoot: string): string | null {
  const applied = readTemplateVersion(projectRoot);
  if (applied === INDUSTRIAL_TEMPLATE_VERSION) return null;
  return `shell template v${applied ?? "?"} → v${INDUSTRIAL_TEMPLATE_VERSION} (run: rn shell refresh)`;
}

export function applyIndustrialShell(projectRoot: string): void {
  if (!existsSync(path.join(projectRoot, "package.json"))) {
    throw new CliError("not a project root (package.json missing)", EXIT_FAIL);
  }
  const moduleId = defaultModuleIdFromManifest(projectRoot);

  for (const rel of INDUSTRIAL_SHELL_FILES) {
    const outRel = rel.replace(/\.template$/, "");
    const out = path.join(projectRoot, outRel);
    mkdirSync(path.dirname(out), { recursive: true });
    writeFileSync(out, renderTemplate(rel, moduleId), "utf8");
  }

  // Ensure the generated registry placeholder exists so module register can fill it.
  const reg = path.join(projectRoot, "shell", "generated-registrations.ts");
  if (!existsSync(reg)) {
    mkdirSync(path.dirname(reg), { recursive: true });
    writeFileSync(
      reg,
      `/** Generated by rn module register — the shell's ModuleRegistry consumes this. */\nimport { registerModule } from "./ModuleRegistry";\nexport function ensureGeneratedRegistrations(): void {}\n`,
      "utf8",
    );
  }

  linkPlatformPackages(projectRoot);

  // SEAM-1/F20: fresh industrial init bakes the loopback cleartext config so
  // device OTA over adb reverse works out of the box (was a manual fix on every
  // new project). Loopback-only — no broad cleartext.
  bakeNetworkSecurityConfig(projectRoot);

  // SEAM-2 (F13/F23): init tail regenerates ALL declaration-derived artifacts
  // (registry + host-resolver + generated-runtime) so the init product is a
  // complete runnable chain (D4), and the OTA base URL has a config seam.
  ensureRuntimeConfig(projectRoot, {});
  regenerateDerivedArtifacts(projectRoot);

  // F19 (G8): release hygiene default — release bundles must never carry dev=true.
  bakeReleaseHygiene(projectRoot);

  writeTemplateVersion(projectRoot);
}

/**
 * G2 (D4) / G4 (BF): locate a native OTA adapter registration under `android/`.
 * Any of: an OtaModule.kt / OtaPackage.kt file, or a *Application.kt whose body
 * references "OtaPackage" (apply-ota signature). Bounded recursive walk — never
 * follows into node_modules / build / .gradle. Returns the first match path or
 * null. Shared by the GF product probe (nativeOtaAdapterPresent) and the BF
 * host probe (brownfield-doctor) so the adapter shape stays defined once.
 */
export function findNativeOtaAdapterPath(projectRoot: string): string | null {
  const androidRoot = path.join(projectRoot, "android");
  if (!existsSync(androidRoot)) return null;
  const queue = [androidRoot];
  const maxVisited = 40_000;
  let visited = 0;
  while (queue.length > 0 && visited < maxVisited) {
    const dir = queue.shift()!;
    visited += 1;
    let entries: string[] = [];
    try {
      entries = readdirSync(dir, { withFileTypes: true }).map((e) => e.name);
    } catch {
      continue;
    }
    for (const name of entries) {
      const abs = path.join(dir, name);
      if (name === "node_modules" || name === "build" || name === ".gradle") {
        continue;
      }
      if (name === "OtaModule.kt" || name === "OtaPackage.kt") {
        return abs;
      }
      if (name.endsWith("Application.kt")) {
        try {
          const body = readFileSync(abs, "utf8");
          if (body.includes("OtaPackage")) return abs;
        } catch {
          /* unreadable — skip */
        }
      }
      try {
        if (statSync(abs).isDirectory()) queue.push(abs);
      } catch {
        /* not a dir — skip */
      }
    }
  }
  return null;
}

/**
 * G2 (D4): is the project's native side wired with the OTA adapter?
 * True when the android source tree contains an OtaModule.kt / OtaPackage.kt,
 * or MainApplication.kt already registers OtaPackage (apply-ota signature).
 * Shares the walk with the BF probe (findNativeOtaAdapterPath) so the adapter
 * shape is defined once.
 */
export function nativeOtaAdapterPresent(projectRoot: string): boolean {
  return findNativeOtaAdapterPath(projectRoot) != null;
}

/**
 * F19 (G8): release-hygiene hardening — ensure android/app/build.gradle carries
 * an ACTIVE (uncommented) `debuggableVariants` inside the `react {}` block so a
 * release bundle is never skipped. In RN 0.87 the property lives on the `react`
 * extension (ReactExtension.kt), NOT on `android {}` — inserting it under
 * `android {` breaks the build (AGP: unknown property). The RN default is
 * ['debug','debugOptimized'], which already bundles release with --dev false;
 * this hardening makes the intent explicit and blocks accidental flavor edits.
 * Best-effort: uncomment an existing commented line inside react {}, else insert
 * after the `react {` opener. Never throws on unexpected gradle shapes.
 */
export function bakeReleaseHygiene(projectRoot: string): void {
  const gradle = path.join(projectRoot, "android", "app", "build.gradle");
  if (!existsSync(gradle)) return;
  let body: string;
  try {
    body = readFileSync(gradle, "utf8");
  } catch {
    return;
  }
  // Target the react {} block (where RN's ReactExtension.debbuggableVariants
  // lives). An ACTIVE line anywhere in the file is fine — it just must not be
  // the RN default comment that could be misread as intent to skip release.
  const active = /^\s*debuggableVariants\s*=/m;
  if (active.test(body)) return;
  const commented = /^\s*\/\/\s*debuggableVariants\s*=[^\n]*$/m;
  if (commented.test(body)) {
    // Replace the WHOLE commented line (RN template: `// debuggableVariants =
    // ["liteDebug", ...]`) — a prefix-only replace would leave the array tail.
    body = body.replace(commented, "    debuggableVariants = []");
  } else {
    // No line at all — insert right after the `react {` block opener.
    const open = /^react\s*\{$/m;
    if (open.test(body)) {
      body = body.replace(open, "react {\n    debuggableVariants = []");
    } else {
      return;
    }
  }
  try {
    writeFileSync(gradle, body, "utf8");
  } catch {
    /* best-effort */
  }
}

/** F20: loopback-only cleartext for device OTA (127.0.0.1/localhost). */
function bakeNetworkSecurityConfig(projectRoot: string): void {
  const xmlDir = path.join(projectRoot, "android/app/src/main/res/xml");
  const xml = path.join(xmlDir, "network_security_config.xml");
  mkdirSync(xmlDir, { recursive: true });
  writeFileSync(
    xml,
    `<?xml version="1.0" encoding="utf-8"?>
<network-security-config>
    <domain-config cleartextTrafficPermitted="true">
        <domain includeSubdomains="false">127.0.0.1</domain>
        <domain includeSubdomains="false">localhost</domain>
    </domain-config>
</network-security-config>
`,
    "utf8",
  );
  const manifest = path.join(
    projectRoot,
    "android/app/src/main/AndroidManifest.xml",
  );
  if (!existsSync(manifest)) return;
  let body = readFileSync(manifest, "utf8");
  if (!body.includes("networkSecurityConfig")) {
    body = body.replace(
      /android:icon="@mipmap\/ic_launcher"/,
      'android:icon="@mipmap/ic_launcher"\n      android:networkSecurityConfig="@xml/network_security_config"',
    );
    writeFileSync(manifest, body, "utf8");
  }
}

/**
 * Link the platform packages (core / shell-core / rn-engine) into the project.
 * Declares them in package.json + symlinks node_modules/@client-platform/* to the
 * platform workspace (local dev). A distributed platform publishes these instead.
 */
function linkPlatformPackages(projectRoot: string): void {
  // N9: locate the platform packages from the CLI's OWN repo root (this
  // checkout / install home), not from an assumed sibling path under the
  // project. A bare "../client-platform-labs/rn" default breaks any project
  // that lives elsewhere (e.g. /tmp or a company workspace) — core/rn-engine
  // silently never linked. CLIENT_PLATFORM_ROOT overrides when the CLI is a
  // symlinked install pointing elsewhere.
  const platformRoot =
    process.env.CLIENT_PLATFORM_ROOT ?? path.resolve(__dirname, "../../..");
  const pkgPath = path.join(projectRoot, "package.json");
  if (!existsSync(pkgPath)) return;
  let pkg: Record<string, unknown>;
  try {
    pkg = JSON.parse(readFileSync(pkgPath, "utf8"));
  } catch {
    return;
  }
  const deps = (pkg["dependencies"] as Record<string, string>) ?? {};
  const platformRootAbs = path.resolve(platformRoot);
  for (const name of ["core", "shell-core", "rn-engine"]) {
    const scoped = `@client-platform/${name}`;
    const src = path.join(platformRootAbs, "packages", name);
    if (!existsSync(src)) continue;
    // N7: private workspace packages are NOT published to npm — a bare version
    // spec makes `npm install` 404. Use a file: spec to the same source the
    // symlink points at, so the package.json is resolvable standalone.
    deps[scoped] = deps[scoped] ?? `file:${src}`;
    const dest = path.join(
      projectRoot,
      "node_modules",
      "@client-platform",
      name,
    );
    mkdirSync(path.dirname(dest), { recursive: true });
    try {
      if (existsSync(dest)) rmSync(dest, { recursive: true, force: true });
      symlinkSync(src, dest, "dir");
    } catch {
      /* symlink may fail on some setups; node_modules install handles it later */
    }
  }
  pkg["dependencies"] = deps;
  writeFileSync(pkgPath, JSON.stringify(pkg, null, 2) + "\n", "utf8");
}

/**
 * F25: regenerate the industrial shell from the CURRENT template (shell files +
 * derived artifacts + template version). Existing projects can catch up with
 * template fixes without re-initing. Refreshing is idempotent — it does not
 * touch dev-session / modules / user business code.
 */
export function refreshIndustrialShell(projectRoot: string): void {
  applyIndustrialShell(projectRoot);
}
