/**
 * Industrial shell generation (ADR-021): turn a basic `rn init` app into the
 * industrial shell — ShellHost + ModuleRegistry (consuming the generated
 * registry) + OTA gate. Zero reference-host coupling (no tiangong/hermes).
 */
import {
  existsSync,
  mkdirSync,
  readFileSync,
  rmSync,
  symlinkSync,
  writeFileSync,
} from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

import { MANIFEST_FILENAME } from "@client-platform/core";
import { CliError, EXIT_FAIL } from "./errors.js";
import {
  ensureRuntimeConfig,
  regenerateDerivedArtifacts,
} from "./declaration-derived.js";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
// dist: packages/rn/dist/industrial-shell.js → templates at packages/rn/templates
const TEMPLATE_ROOT = path.resolve(__dirname, "../templates/industrial-shell");

export const INDUSTRIAL_SHELL_FILES = [
  "App.tsx.template",
  "shell/ShellHost.tsx.template",
  "shell/ModuleRegistry.ts.template",
  "shell/hostContext.ts.template",
  "shell/FailedUI.tsx.template",
  "shell/ota/slotPaths.ts.template",
  "metro.config.js.template",
] as const;

function renderTemplate(rel: string, defaultModuleId: string): string {
  const src = readFileSync(path.join(TEMPLATE_ROOT, rel), "utf8");
  return src.replace(/{{DEFAULT_MODULE_ID}}/g, defaultModuleId);
}

/** Read the project's default module id from its manifest (or fall back). */
function defaultModuleIdFromManifest(projectRoot: string): string {
  try {
    const raw = readFileSync(
      path.join(projectRoot, MANIFEST_FILENAME),
      "utf8",
    );
    // minimal JSONC read: business default is "main" per topology-b; the
    // manifest doesn't carry it, so default to "main".
    void raw;
  } catch {
    /* ignore */
  }
  return "main";
}

/**
 * Apply the industrial shell to an initialized project.
 * Writes App.tsx (→ ShellHost) + shell/{ShellHost,ModuleRegistry,hostContext,FailedUI,ota/slotPaths}
 * + links the platform packages (core/shell-core/rn-engine) so the shell resolves them.
 */
/** F25: template version — bump when industrial shell templates change. Existing
 * projects can detect drift and run `rn shell refresh` to regenerate. */
export const INDUSTRIAL_TEMPLATE_VERSION = "2";

/** Write the applied template version marker (.rn/template-version.json). */
export function writeTemplateVersion(projectRoot: string): void {
  const file = path.join(projectRoot, ".rn", "template-version.json");
  mkdirSync(path.dirname(file), { recursive: true });
  writeFileSync(
    file,
    `${JSON.stringify({ schemaVersion: 1, industrialTemplateVersion: INDUSTRIAL_TEMPLATE_VERSION }, null, 2)}\n`,
    "utf8",
  );
}

/** Read the project's applied template version (null when not industrial). */
export function readTemplateVersion(projectRoot: string): string | null {
  try {
    const j = JSON.parse(
      readFileSync(path.join(projectRoot, ".rn", "template-version.json"), "utf8"),
    ) as { industrialTemplateVersion?: string };
    return j.industrialTemplateVersion ?? null;
  } catch {
    return null;
  }
}

/** F25: does this project's shell drift from the current template? */
export function shellTemplateDrift(projectRoot: string): string | null {
  const applied = readTemplateVersion(projectRoot);
  if (applied === INDUSTRIAL_TEMPLATE_VERSION) return null;
  return `shell template v${applied ?? "?"} → v${INDUSTRIAL_TEMPLATE_VERSION} (run: rn shell refresh)`;
}

export function applyIndustrialShell(projectRoot: string): void {
  if (!existsSync(path.join(projectRoot, "package.json"))) {
    throw new CliError("not a project root (package.json missing)", EXIT_FAIL);
  }
  const moduleId = defaultModuleIdFromManifest(projectRoot);

  for (const rel of INDUSTRIAL_SHELL_FILES) {
    const outRel = rel.replace(/\.template$/, "");
    const out = path.join(projectRoot, outRel);
    mkdirSync(path.dirname(out), { recursive: true });
    writeFileSync(out, renderTemplate(rel, moduleId), "utf8");
  }

  // Ensure the generated registry placeholder exists so module register can fill it.
  const reg = path.join(projectRoot, "shell", "generated-registrations.ts");
  if (!existsSync(reg)) {
    mkdirSync(path.dirname(reg), { recursive: true });
    writeFileSync(
      reg,
      `/** Generated by rn module register — the shell's ModuleRegistry consumes this. */\nimport { registerModule } from "./ModuleRegistry";\nexport function ensureGeneratedRegistrations(): void {}\n`,
      "utf8",
    );
  }

  linkPlatformPackages(projectRoot);

  // SEAM-1/F20: fresh industrial init bakes the loopback cleartext config so
  // device OTA over adb reverse works out of the box (was a manual fix on every
  // new project). Loopback-only — no broad cleartext.
  bakeNetworkSecurityConfig(projectRoot);

  // SEAM-2 (F13/F23): init tail regenerates ALL declaration-derived artifacts
  // (registry + host-resolver + generated-runtime) so the init product is a
  // complete runnable chain (D4), and the OTA base URL has a config seam.
  ensureRuntimeConfig(projectRoot, {});
  regenerateDerivedArtifacts(projectRoot);
  writeTemplateVersion(projectRoot);
}

/** F20: loopback-only cleartext for device OTA (127.0.0.1/localhost). */
function bakeNetworkSecurityConfig(projectRoot: string): void {
  const xmlDir = path.join(
    projectRoot,
    "android/app/src/main/res/xml",
  );
  const xml = path.join(xmlDir, "network_security_config.xml");
  mkdirSync(xmlDir, { recursive: true });
  writeFileSync(
    xml,
    `<?xml version="1.0" encoding="utf-8"?>
<network-security-config>
    <domain-config cleartextTrafficPermitted="true">
        <domain includeSubdomains="false">127.0.0.1</domain>
        <domain includeSubdomains="false">localhost</domain>
    </domain-config>
</network-security-config>
`,
    "utf8",
  );
  const manifest = path.join(
    projectRoot,
    "android/app/src/main/AndroidManifest.xml",
  );
  if (!existsSync(manifest)) return;
  let body = readFileSync(manifest, "utf8");
  if (!body.includes("networkSecurityConfig")) {
    body = body.replace(
      /android:icon="@mipmap\/ic_launcher"/,
      'android:icon="@mipmap/ic_launcher"\n      android:networkSecurityConfig="@xml/network_security_config"',
    );
    writeFileSync(manifest, body, "utf8");
  }
}

/**
 * Link the platform packages (core / shell-core / rn-engine) into the project.
 * Declares them in package.json + symlinks node_modules/@client-platform/* to the
 * platform workspace (local dev). A distributed platform publishes these instead.
 */
function linkPlatformPackages(projectRoot: string): void {
  const platformRoot =
    process.env.CLIENT_PLATFORM_ROOT ??
    path.resolve(projectRoot, "..", "client-platform-labs", "rn");
  const pkgPath = path.join(projectRoot, "package.json");
  if (!existsSync(pkgPath)) return;
  let pkg: Record<string, unknown>;
  try {
    pkg = JSON.parse(readFileSync(pkgPath, "utf8"));
  } catch {
    return;
  }
  const deps = (pkg["dependencies"] as Record<string, string>) ?? {};
  for (const name of ["core", "shell-core", "rn-engine"]) {
    const scoped = `@client-platform/${name}`;
    const src = path.join(platformRoot, "packages", name);
    if (!existsSync(src)) continue;
    deps[scoped] = deps[scoped] ?? "0.1.0";
    const dest = path.join(projectRoot, "node_modules", "@client-platform", name);
    mkdirSync(path.dirname(dest), { recursive: true });
    try {
      if (existsSync(dest)) rmSync(dest, { recursive: true, force: true });
      symlinkSync(src, dest, "dir");
    } catch {
      /* symlink may fail on some setups; node_modules install handles it later */
    }
  }
  pkg["dependencies"] = deps;
  writeFileSync(pkgPath, JSON.stringify(pkg, null, 2) + "\n", "utf8");
}

/**
 * F25: regenerate the industrial shell from the CURRENT template (shell files +
 * derived artifacts + template version). Existing projects can catch up with
 * template fixes without re-initing. Refreshing is idempotent — it does not
 * touch dev-session / modules / user business code.
 */
export function refreshIndustrialShell(projectRoot: string): void {
  applyIndustrialShell(projectRoot);
}
