/**
 * Industrial shell generation (ADR-021): turn a basic `rn init` app into the
 * industrial shell — ShellHost + ModuleRegistry (consuming the generated
 * registry) + OTA gate. Zero reference-host coupling (no tiangong/hermes).
 */
import {
  existsSync,
  mkdirSync,
  readFileSync,
  rmSync,
  symlinkSync,
  writeFileSync,
} from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

import { MANIFEST_FILENAME } from "@client-platform/core";
import { CliError, EXIT_FAIL } from "./errors.js";
import {
  ensureRuntimeConfig,
  regenerateDerivedArtifacts,
} from "./declaration-derived.js";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
// dist: packages/rn/dist/industrial-shell.js → templates at packages/rn/templates
const TEMPLATE_ROOT = path.resolve(__dirname, "../templates/industrial-shell");

export const INDUSTRIAL_SHELL_FILES = [
  "App.tsx.template",
  "shell/ShellHost.tsx.template",
  "shell/ModuleRegistry.ts.template",
  "shell/hostContext.ts.template",
  "shell/FailedUI.tsx.template",
  "shell/ota/slotPaths.ts.template",
  "metro.config.js.template",
] as const;

function renderTemplate(rel: string, defaultModuleId: string): string {
  const src = readFileSync(path.join(TEMPLATE_ROOT, rel), "utf8");
  return src.replace(/{{DEFAULT_MODULE_ID}}/g, defaultModuleId);
}

/** Read the project's default module id from its manifest (or fall back). */
function defaultModuleIdFromManifest(projectRoot: string): string {
  try {
    const raw = readFileSync(
      path.join(projectRoot, MANIFEST_FILENAME),
      "utf8",
    );
    // minimal JSONC read: business default is "main" per topology-b; the
    // manifest doesn't carry it, so default to "main".
    void raw;
  } catch {
    /* ignore */
  }
  return "main";
}

/**
 * Apply the industrial shell to an initialized project.
 * Writes App.tsx (→ ShellHost) + shell/{ShellHost,ModuleRegistry,hostContext,FailedUI,ota/slotPaths}
 * + links the platform packages (core/shell-core/rn-engine) so the shell resolves them.
 */
export function applyIndustrialShell(projectRoot: string): void {
  if (!existsSync(path.join(projectRoot, "package.json"))) {
    throw new CliError("not a project root (package.json missing)", EXIT_FAIL);
  }
  const moduleId = defaultModuleIdFromManifest(projectRoot);

  for (const rel of INDUSTRIAL_SHELL_FILES) {
    const outRel = rel.replace(/\.template$/, "");
    const out = path.join(projectRoot, outRel);
    mkdirSync(path.dirname(out), { recursive: true });
    writeFileSync(out, renderTemplate(rel, moduleId), "utf8");
  }

  // Ensure the generated registry placeholder exists so module register can fill it.
  const reg = path.join(projectRoot, "shell", "generated-registrations.ts");
  if (!existsSync(reg)) {
    mkdirSync(path.dirname(reg), { recursive: true });
    writeFileSync(
      reg,
      `/** Generated by rn module register — the shell's ModuleRegistry consumes this. */\nimport { registerModule } from "./ModuleRegistry";\nexport function ensureGeneratedRegistrations(): void {}\n`,
      "utf8",
    );
  }

  linkPlatformPackages(projectRoot);

  // SEAM-2 (F13/F23): init tail regenerates ALL declaration-derived artifacts
  // (registry + host-resolver + generated-runtime) so the init product is a
  // complete runnable chain (D4), and the OTA base URL has a config seam.
  ensureRuntimeConfig(projectRoot, {});
  regenerateDerivedArtifacts(projectRoot);
}

/**
 * Link the platform packages (core / shell-core / rn-engine) into the project.
 * Declares them in package.json + symlinks node_modules/@client-platform/* to the
 * platform workspace (local dev). A distributed platform publishes these instead.
 */
function linkPlatformPackages(projectRoot: string): void {
  const platformRoot =
    process.env.CLIENT_PLATFORM_ROOT ??
    path.resolve(projectRoot, "..", "client-platform-labs", "rn");
  const pkgPath = path.join(projectRoot, "package.json");
  if (!existsSync(pkgPath)) return;
  let pkg: Record<string, unknown>;
  try {
    pkg = JSON.parse(readFileSync(pkgPath, "utf8"));
  } catch {
    return;
  }
  const deps = (pkg["dependencies"] as Record<string, string>) ?? {};
  for (const name of ["core", "shell-core", "rn-engine"]) {
    const scoped = `@client-platform/${name}`;
    const src = path.join(platformRoot, "packages", name);
    if (!existsSync(src)) continue;
    deps[scoped] = deps[scoped] ?? "0.1.0";
    const dest = path.join(projectRoot, "node_modules", "@client-platform", name);
    mkdirSync(path.dirname(dest), { recursive: true });
    try {
      if (existsSync(dest)) rmSync(dest, { recursive: true, force: true });
      symlinkSync(src, dest, "dir");
    } catch {
      /* symlink may fail on some setups; node_modules install handles it later */
    }
  }
  pkg["dependencies"] = deps;
  writeFileSync(pkgPath, JSON.stringify(pkg, null, 2) + "\n", "utf8");
}
