/**
 * Host Metro resolver file generation + audit (platform; map #149 / #158).
 */
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { createRequire } from "node:module";
import path from "node:path";

import {
  auditHostMetroNodeModulesPaths,
  buildHostMetroMergeConfig,
  type HostMetroMergeConfig,
} from "@client-platform/rn-core";

import { loadDevSessionConfig } from "./dev-session-config.js";

export const HOST_METRO_RESOLVER_RELATIVE = path.join(
  ".rn",
  "metro",
  "host-resolver.cjs",
);

export function hostMetroResolverPath(projectRoot: string): string {
  return path.join(projectRoot, HOST_METRO_RESOLVER_RELATIVE);
}

/** Default @tiangong/* package alias roots for sibling repos. */
export function defaultBusinessPackageAliases(
  hostRoot: string,
  moduleIds: readonly string[],
): Record<string, string> {
  const out: Record<string, string> = {};
  for (const id of moduleIds) {
    const sibling = path.join(hostRoot, "..", id);
    if (existsSync(sibling)) {
      out[`@tiangong/${id}`] = sibling;
    }
  }
  return out;
}

export function resolveHostBusinessWatchFolders(
  hostRoot: string,
  moduleIds: readonly string[],
): string[] {
  const folders: string[] = [];
  for (const id of moduleIds) {
    const sibling = path.resolve(hostRoot, "..", id);
    if (existsSync(sibling)) {
      folders.push(sibling);
    }
  }
  return folders;
}

export function buildHostMetroConfigForProject(
  projectRoot: string,
  options?: {
    watchFolders?: string[];
    packageAliases?: Record<string, string>;
  },
): HostMetroMergeConfig {
  const hostRoot = path.resolve(projectRoot);
  const session = loadDevSessionConfig(hostRoot);
  const moduleIds = session ? Object.keys(session.modules) : [];
  const watchFolders =
    options?.watchFolders ??
    resolveHostBusinessWatchFolders(hostRoot, moduleIds);
  const packageAliases =
    options?.packageAliases ?? defaultBusinessPackageAliases(hostRoot, moduleIds);

  return buildHostMetroMergeConfig({
    hostRoot,
    watchFolders,
    packageAliases,
  });
}

export function renderHostMetroResolverCjsStandalone(
  config: HostMetroMergeConfig,
): string {
  return `/**
 * Auto-generated by @client-platform/rn — Host Metro resolver (singleton React policy).
 * Regenerated by: rn dev · rn module register
 */
"use strict";
const path = require("node:path");

const WATCH_FOLDERS = ${JSON.stringify(config.watchFolders, null, 2)};
const NODE_MODULES_PATHS = ${JSON.stringify(config.resolver.nodeModulesPaths, null, 2)};
const EXTRA_NODE_MODULES = ${JSON.stringify(config.resolver.extraNodeModules, null, 2)};
const DISABLE_HIERARCHICAL_LOOKUP = ${config.resolver.disableHierarchicalLookup};

function load() {
  return {
    watchFolders: WATCH_FOLDERS,
    resolver: {
      nodeModulesPaths: NODE_MODULES_PATHS,
      extraNodeModules: EXTRA_NODE_MODULES,
      disableHierarchicalLookup: DISABLE_HIERARCHICAL_LOOKUP,
    },
  };
}

module.exports = { load };
`;
}

export function writeHostMetroResolver(
  projectRoot: string,
  options?: Parameters<typeof buildHostMetroConfigForProject>[1],
): string {
  const config = buildHostMetroConfigForProject(projectRoot, options);
  const file = hostMetroResolverPath(projectRoot);
  mkdirSync(path.dirname(file), { recursive: true });
  writeFileSync(file, renderHostMetroResolverCjsStandalone(config), "utf8");
  return file;
}

export function renderHostMetroConfigJs(): string {
  return `const path = require("node:path");
const { getDefaultConfig, mergeConfig } = require("@react-native/metro-config");

const hostRoot = __dirname;
const resolverPath = path.join(hostRoot, ".rn/metro/host-resolver.cjs");

let hostMetro = {};
try {
  hostMetro = require(resolverPath).load();
} catch (err) {
  console.warn(
    "[rn] missing or invalid .rn/metro/host-resolver.cjs — run: rn module register (or rn dev)",
  );
}

module.exports = mergeConfig(getDefaultConfig(hostRoot), hostMetro);
`;
}

export function auditHostMetroResolverFile(projectRoot: string): string[] {
  const file = hostMetroResolverPath(projectRoot);
  if (!existsSync(file)) {
    return ["missing .rn/metro/host-resolver.cjs — run rn dev / rn module register"];
  }
  const req = createRequire(import.meta.url);
  const mod = req(file) as {
    load: () => HostMetroMergeConfig;
  };
  const cfg = mod.load();
  return auditHostMetroNodeModulesPaths({
    nodeModulesPaths: cfg.resolver.nodeModulesPaths,
    watchFolders: cfg.watchFolders,
  });
}

export function auditHostMetroConfigOnDisk(projectRoot: string): string[] {
  const issues = auditHostMetroResolverFile(projectRoot);
  const metroConfig = path.join(projectRoot, "metro.config.js");
  if (!existsSync(metroConfig)) {
    issues.push("missing metro.config.js");
    return issues;
  }
  const src = readFileSync(metroConfig, "utf8");
  if (!src.includes("host-resolver.cjs") && src.includes("nodeModulesPaths")) {
    for (const line of src.split("\n")) {
      if (line.includes("node_modules") && line.includes("../")) {
        issues.push(
          "metro.config.js may resolve business node_modules — use .rn/metro/host-resolver.cjs",
        );
        break;
      }
    }
  }
  return issues;
}
