import { mkdirSync, writeFileSync, existsSync, rmSync, readdirSync } from "node:fs";
import path from "node:path";

import type { DevSessionConfig } from "@client-platform/core";

export const METRO_MODULE_DIR = path.join(".rn", "metro");

/**
 * Per-module Metro config (CJS) — isolates transformer cache via cacheVersion.
 * Entry file is selected by the bundle URL path (e.g. /index.support.bundle).
 */
export function metroModuleConfigPath(projectRoot: string, moduleId: string): string {
  return path.join(projectRoot, METRO_MODULE_DIR, `${moduleId}.config.cjs`);
}

export function renderMetroModuleConfig(options: {
  moduleId: string;
  entry?: string;
}): string {
  const entry = options.entry ?? "index";
  return `/**
 * Auto-generated by @client-platform/rn (map-a/#17).
 * Module: ${options.moduleId} · preferred entry: ${entry}
 * Do not edit by hand — regenerated by rn demo add / rn dev --modules.
 */
const path = require("node:path");
const { getDefaultConfig, mergeConfig } = require("@react-native/metro-config");

const projectRoot = path.resolve(__dirname, "../..");
const defaultConfig = getDefaultConfig(projectRoot);

// SEAM-2/F17: inherit the host resolver (platform-package resolution) so the
// module dev Metro resolves @client-platform/* exactly like the host shell —
// one resolver contract for dev and release.
let hostResolver = {};
try {
  hostResolver = require("./host-resolver.cjs").load();
} catch (e) {
  console.warn(
    "[rn] host-resolver.cjs missing — platform packages may not resolve; run rn module register",
  );
}

module.exports = mergeConfig(defaultConfig, {
  projectRoot,
  cacheVersion: "rn-module-${options.moduleId}",
  resetCache: false,
  watchFolders: hostResolver.watchFolders ?? [],
  resolver: {
    ...defaultConfig.resolver,
    ...(hostResolver.resolver ?? {}),
  },
  server: {
    ...defaultConfig.server,
    enhanceMiddleware: (middleware) => {
      return (req, res, next) => {
        res.setHeader("X-RN-Business-Module", "${options.moduleId}");
        res.setHeader("X-RN-Bundle-Kind", "base");
        return middleware(req, res, next);
      };
    },
  },
});
`;
}

export function writeMetroModuleConfigs(
  projectRoot: string,
  config: DevSessionConfig,
): string[] {
  const dir = path.join(projectRoot, METRO_MODULE_DIR);
  mkdirSync(dir, { recursive: true });
  const written: string[] = [];
  for (const [moduleId, binding] of Object.entries(config.modules)) {
    const file = metroModuleConfigPath(projectRoot, moduleId);
    writeFileSync(
      file,
      renderMetroModuleConfig({
        moduleId,
        entry: binding.entry,
      }),
      "utf8",
    );
    written.push(file);
  }
  return written;
}

export function removeMetroModuleConfigs(projectRoot: string): void {
  const dir = path.join(projectRoot, METRO_MODULE_DIR);
  if (!existsSync(dir)) {
    return;
  }
  for (const name of readdirSync(dir)) {
    rmSync(path.join(dir, name), { force: true });
  }
  try {
    rmSync(dir, { recursive: true, force: true });
  } catch {
    // ignore non-empty / race
  }
}
