/**
 * SEAM-2 (R2): 声明→运行时配置/派生物接缝.
 *
 * `.rn/runtime.jsonc` is the single source of truth for runtime configuration
 * (CP base URL, device OTA pubkeys). `shell/generated-runtime.ts` is the
 * derived artifact consumed by the industrial shell. Regenerated by rn init /
 * rn module register (see declaration-derived.ts). Missing config fails loud
 * in the shell instead of silently skipping OTA (F23).
 */
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";

export const RUNTIME_CONFIG_RELATIVE = path.join(".rn", "runtime.jsonc");
export const GENERATED_RUNTIME_RELATIVE = path.join(
  "shell",
  "generated-runtime.ts",
);

export type RuntimeConfig = {
  /** Control-plane base URL (device OTA check/download target). Empty = not configured. */
  cpBaseUrl?: string;
  /** Ed25519 public keys (hex) baked into the OTA native module. */
  otaPubKeys?: string[];
};

export function runtimeConfigPath(projectRoot: string): string {
  return path.join(projectRoot, RUNTIME_CONFIG_RELATIVE);
}

/** Read `.rn/runtime.jsonc` (JSONC: tolerates `//` comment lines). */
export function loadRuntimeConfig(projectRoot: string): RuntimeConfig {
  const file = runtimeConfigPath(projectRoot);
  if (!existsSync(file)) return {};
  try {
    const raw = readFileSync(file, "utf8")
      .split("\n")
      .filter((l) => !l.trim().startsWith("//"))
      .join("\n");
    const parsed = JSON.parse(raw) as {
      cpBaseUrl?: string;
      otaPubKeys?: string[];
    };
    return {
      cpBaseUrl:
        typeof parsed.cpBaseUrl === "string" && parsed.cpBaseUrl.length > 0
          ? parsed.cpBaseUrl
          : undefined,
      otaPubKeys: Array.isArray(parsed.otaPubKeys)
        ? parsed.otaPubKeys.filter(
            (k): k is string => typeof k === "string" && k.length === 64,
          )
        : undefined,
    };
  } catch {
    return {};
  }
}

/** Write the declared runtime config (default on init; single source of truth). */
export function writeRuntimeConfig(
  projectRoot: string,
  cfg: RuntimeConfig,
): string {
  const file = runtimeConfigPath(projectRoot);
  mkdirSync(path.dirname(file), { recursive: true });
  const json = JSON.stringify({ schemaVersion: 1, ...cfg }, null, 2);
  writeFileSync(
    file,
    `// Runtime config — single source of truth (SEAM-2). Regenerated/kept by rn init / rn module register.
// cpBaseUrl: your control plane (device OTA check/download). Leave empty + the shell
// fails loud on boot (F23). otaPubKeys: Ed25519 pubkeys (hex) baked into the OTA module.
${json}
`,
    "utf8",
  );
  return file;
}

/** Render `shell/generated-runtime.ts` from the declared config. */
export function renderGeneratedRuntime(cfg: RuntimeConfig): string {
  return `/**
 * Auto-generated by rn (SEAM-2) — do not edit. Regenerated by rn init / rn module register.
 * Declared from .rn/runtime.jsonc (single source of truth for runtime config).
 */
export const cpBaseUrl: string = ${JSON.stringify(cfg.cpBaseUrl ?? "")};
export const otaPubKeys: string[] = ${JSON.stringify(cfg.otaPubKeys ?? [])};
`;
}

export function writeGeneratedRuntime(projectRoot: string): string {
  const file = path.join(projectRoot, GENERATED_RUNTIME_RELATIVE);
  mkdirSync(path.dirname(file), { recursive: true });
  writeFileSync(file, renderGeneratedRuntime(loadRuntimeConfig(projectRoot)), "utf8");
  return file;
}
